[project]
name = "wallhavend"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  python = "^3.11",
  requests = "^2.31.0",
  rich = "^13.0.1"
]